// Bundles the branch's backend seed JSON into seed.js for the preview API stub.
// Usage (from the repo root): node preview-api-stub/make-seed.mjs [repoRoot]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const NAMES = ['ministries', 'church', 'events', 'regions', 'news'];
const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(process.argv[2] ?? process.cwd());

const seed = {};
for (const name of NAMES) {
  const file = join(root, 'backend', 'app', `${name}.json`);
  // Branches only carry the files their backend uses; the stub treats missing keys as empty.
  if (existsSync(file)) seed[name] = JSON.parse(readFileSync(file, 'utf8'));
}

const out = join(here, 'seed.js');
writeFileSync(out, `// Generated by make-seed.mjs from backend/app/*.json. Do not edit.\nexport const SEED = ${JSON.stringify(seed, null, 2)};\n`);
console.log(`wrote ${out} with: ${Object.keys(seed).join(', ') || '(no seed files found)'}`);
