// Generated by make-seed.mjs from backend/app/*.json. Do not edit.
export const SEED = {
  "ministries": [
    {
      "name": "Kids & families",
      "category": "Next generation",
      "icon": "☀",
      "filled": 32,
      "total": 48,
      "description": "Welcome families, lead activities, and help children feel known in a safe Sunday environment.",
      "skills": [
        "Teaching",
        "Encouragement"
      ],
      "style": "Working with people",
      "day": "Sunday mornings",
      "head": "Sarah Mitchell",
      "note": "Background check and onboarding required.",
      "id": 0,
      "email": "sarah.mitchell@example.com"
    },
    {
      "name": "Welcome team",
      "category": "Hospitality",
      "icon": "✳",
      "filled": 24,
      "total": 32,
      "description": "Greet guests, help with check-in, and make introductions that turn a first visit into belonging.",
      "skills": [
        "Hospitality",
        "Encouragement"
      ],
      "style": "Working with people",
      "day": "Sunday mornings",
      "head": "David Chen",
      "note": "Training provided. A friendly face is a great place to start.",
      "id": 1,
      "email": "david.chen@example.com"
    },
    {
      "name": "Production & media",
      "category": "Creative & worship",
      "icon": "◈",
      "filled": 12,
      "total": 20,
      "description": "Help every message be seen and heard. Support live sound, cameras, slides, and the online service.",
      "skills": [
        "Technology",
        "Creativity"
      ],
      "style": "Behind the scenes",
      "day": "Sunday mornings",
      "head": "Marcus Reed",
      "note": "Shadow an experienced team member before your first service.",
      "id": 2,
      "email": "marcus.reed@example.com"
    },
    {
      "name": "Community outreach",
      "category": "Local impact",
      "icon": "♡",
      "filled": 26,
      "total": 36,
      "description": "Prepare food boxes, support local partners, and care for our neighbors at community events.",
      "skills": [
        "Hospitality",
        "Organization"
      ],
      "style": "Hands-on service",
      "day": "Saturday mornings",
      "head": "Elena Brooks",
      "note": "Flexible opportunities for individuals and families.",
      "id": 3,
      "email": "elena.brooks@example.com"
    },
    {
      "name": "Worship collective",
      "category": "Creative & worship",
      "icon": "♫",
      "filled": 18,
      "total": 22,
      "description": "Create space for worship. Join vocalists and instrumentalists for rehearsals and Sunday services.",
      "skills": [
        "Music",
        "Creativity"
      ],
      "style": "Working with people",
      "day": "Sunday mornings",
      "head": "Jordan Ellis",
      "note": "Audition and midweek rehearsal required.",
      "id": 4,
      "email": "jordan.ellis@example.com"
    },
    {
      "name": "Care & connection",
      "category": "Pastoral care",
      "icon": "⌘",
      "filled": 14,
      "total": 24,
      "description": "Make follow-up calls, coordinate meals, and walk alongside people through life’s changes.",
      "skills": [
        "Listening",
        "Encouragement"
      ],
      "style": "Working with people",
      "day": "Weekday evenings",
      "head": "Rachel Adams",
      "note": "Care training and confidentiality orientation required.",
      "id": 5,
      "email": "rachel.adams@example.com"
    }
  ],
  "regions": [
    {
      "id": 0,
      "country": "Nepal",
      "country_code": "NPL",
      "codename": "Team Highland",
      "field_of_ministry": "Discipleship and community health training in mountain villages",
      "testimony": "We spent the spring walking the ridge trails between villages that a car can never reach, carrying a water-filtration kit and a stack of health pamphlets translated into Nepali. Three families we have met with monthly for two years asked, unprompted, if they could start reading the Gospel of Luke together on Tuesday evenings. A landslide closed the lower trail in March, so the walk to the furthest village now takes an extra four hours each way, and our two porters are stretched thin. We are grateful and tired in about equal measure.",
      "since": 2019,
      "team_size": 4
    },
    {
      "id": 1,
      "country": "Kenya",
      "country_code": "KEN",
      "codename": "Team Rift Valley",
      "field_of_ministry": "Vocational training and church planting among pastoralist communities",
      "testimony": "The welding and tailoring cohort graduated eleven students this term, and four of them have already opened small stalls at the trading center. Attendance at the Wednesday fellowship has tripled since a respected elder in the community started attending after his son's business took off. Prolonged drought has pushed several partner families to migrate further than usual with their herds, which means our teaching schedule now bends around water and grazing, not the calendar. We are learning to plan in seasons, not weeks.",
      "since": 2016,
      "team_size": 6
    },
    {
      "id": 2,
      "country": "Peru",
      "country_code": "PER",
      "codename": "Team Andina",
      "field_of_ministry": "Literacy programs and church partnership in Quechua-speaking highland towns",
      "testimony": "This month we finished translating the children's literacy primer into the local Quechua dialect, a project three village teachers have carried alongside us for over a year. Sunday attendance at the two partner churches keeps growing, mostly from families who first came for the after-school reading sessions. Altitude sickness took one of our newer teammates hard this quarter, and a stretch of heavy rain washed out the road to Ocongate for nearly three weeks, cutting off our furthest teaching site entirely.",
      "since": 2021,
      "team_size": 3
    },
    {
      "id": 3,
      "country": "Thailand",
      "country_code": "THA",
      "codename": "Team Northern Light",
      "field_of_ministry": "Anti-trafficking advocacy and vocational safe houses for at-risk youth",
      "testimony": "Two young women who came through our safe house program a year ago are now training as seamstresses at a partner workshop, earning their first steady wages. We opened conversations with a third village school this term after a teacher there asked us to run an awareness workshop following a recent case in the district. Funding for the safe house's second dormitory fell through in January, so we are currently over capacity and turning away referrals we deeply wish we could take.",
      "since": 2017,
      "team_size": 5
    },
    {
      "id": 4,
      "country": "Albania",
      "country_code": "ALB",
      "codename": "Team Adriatic",
      "field_of_ministry": "Youth mentoring and small church revitalization in post-communist towns",
      "testimony": "The youth group in Shkodër has grown from five teenagers meeting in a living room to over twenty gathering weekly in the church basement, largely through word of mouth after a regional talent night we hosted last fall. Two of the original five are now leading their own small groups. Emigration keeps thinning the town: three families we mentor closely are weighing job offers abroad, and if they leave, our leadership pipeline shrinks by half overnight.",
      "since": 2018,
      "team_size": 3
    },
    {
      "id": 5,
      "country": "Mongolia",
      "country_code": "MNG",
      "codename": "Team Steppe",
      "field_of_ministry": "Herder-community outreach and winter relief logistics",
      "testimony": "We distributed emergency fodder and stove fuel to fourteen herding families ahead of what forecasters are calling a severe dzud winter, working from a list built with a local cooperative we've partnered with for three years. A herder family that lost most of their livestock two winters ago hosted our team's Bible discussion for the first time this month, entirely their own idea. Roads outside Erdenet are already difficult, and if the season turns as hard as predicted, several of our contact families will be unreachable by vehicle for weeks at a time.",
      "since": 2015,
      "team_size": 4
    }
  ],
  "news": [
    {
      "id": 322673112,
      "country": "Nepal",
      "country_code": "NPL",
      "city": "Kathmandu",
      "lat": 27.6163,
      "lng": 85.3362,
      "headline": "Nepal avalanche toll rises to 15 deaths with discovery of 8 bodies on Mount Himlung",
      "source": "Mymotherlode.com - The Mother Lode's Local News, S",
      "date": "2026-10-02",
      "summary": "An avalanche on Mount Himlung killed 15 people, with rescuers finding 8 bodies at the base camp."
    },
    {
      "id": 760374763,
      "country": "Kenya",
      "country_code": "KEN",
      "city": "Nairobi",
      "lat": -1.3272,
      "lng": 36.725,
      "headline": "Nigerian, Cameroon, Sudanese nationals and 14 others arrested in Kenya fake currency, gold scam raid",
      "source": "Latest Nigerian News",
      "date": "2026-10-02",
      "summary": "Investigators arrested Nigerian, Cameroonian, Sudanese nationals and 14 others in a fake currency and gold scam raid."
    },
    {
      "id": 288982397,
      "country": "Kenya",
      "country_code": "KEN",
      "city": "Nairobi",
      "lat": -1.4168,
      "lng": 36.8318,
      "headline": "Food Supply Costs Push Kenya Inflation to 6.8% in September",
      "source": "Business Today Kenya",
      "date": "2026-10-02",
      "summary": "Kenya's inflation rose to 6.8% in September, largely driven by food supply pressure from adverse weather."
    },
    {
      "id": 264272917,
      "country": "Kenya",
      "country_code": "KEN",
      "city": "Nairobi",
      "lat": -1.1911,
      "lng": 36.8999,
      "headline": "UA Legacy Grants Deploys 200 Clean Water Filters In Kakuma, Kenya, Advancing Rapid Clean Water Deployment Model",
      "source": "Menafn",
      "date": "2026-10-02",
      "summary": "UA Legacy Grants deployed 200 clean water filters in Kakuma, Kenya."
    },
    {
      "id": 363521957,
      "country": "Kenya",
      "country_code": "KEN",
      "city": "Nairobi",
      "lat": -1.2385,
      "lng": 36.7671,
      "headline": "Court blocks Kenya from seizing Burundi firm’s cash",
      "source": "The Eastafrican",
      "date": "2026-10-02",
      "summary": "A Kenyan court blocked seizure of a Burundi firm's cash over unsupported withdrawal claims."
    },
    {
      "id": 85007195,
      "country": "Kenya",
      "country_code": "KEN",
      "city": "Nairobi",
      "lat": -1.4146,
      "lng": 36.6778,
      "headline": "Akwaaba African Travel Market for Magical Kenya Travel Expo",
      "source": "Tribune",
      "date": "2026-10-02",
      "summary": "Akwaaba African Travel Market will exhibit at the Nairobi Magical Kenya Travel Expo."
    },
    {
      "id": 732972770,
      "country": "Peru",
      "country_code": "PER",
      "city": "Lima",
      "lat": -12.0078,
      "lng": -76.9321,
      "headline": "U.S. Visa Ban Hits Judge at Center of Chinese Port Dispute in Peru",
      "source": "Supply Chain Brain",
      "date": "2026-10-02",
      "summary": "A U.S. visa ban affects a judge whose decision on the Chinese‑owned Chancay port sparked Washington’s criticism of Peru."
    },
    {
      "id": 691692696,
      "country": "Peru",
      "country_code": "PER",
      "city": "Lima",
      "lat": -12.1464,
      "lng": -77.0746,
      "headline": "Patriot puts 3km Peru silver corridor under microscope",
      "source": "The Sydney Morning Herald",
      "date": "2026-10-02",
      "summary": "Patriot Resources started a major exploration push at its Tassa project after lab samples, aiming to enlarge its silver‑equivalent resource."
    },
    {
      "id": 631744187,
      "country": "Peru",
      "country_code": "PER",
      "city": "Lima",
      "lat": -12.0689,
      "lng": -77.0788,
      "headline": "BBVA Peru Provides Financing for Prize Group’s Blueberry Project in Peru",
      "source": "Global Legal Chronicle",
      "date": "2026-10-02",
      "summary": "BBVA Peru structured a medium‑term financing arrangement for the Prize Group, with Cuatrecasas as its advisor."
    },
    {
      "id": 233058290,
      "country": "Peru",
      "country_code": "PER",
      "city": "Lima",
      "lat": -12.1448,
      "lng": -77.1765,
      "headline": "Father Fights for Return of Six‑Year‑Old Son Held in Peru After Abduction by Ex‑Wife",
      "source": "Headtopics",
      "date": "2026-10-01",
      "summary": "A London father is requesting the return of his son, who was taken to Peru by his ex‑wife."
    },
    {
      "id": 188334381,
      "country": "Peru",
      "country_code": "PER",
      "city": "Lima",
      "lat": -11.9746,
      "lng": -77.1796,
      "headline": "'Heartbroken' British father fears he'll never see his six-year-old son again after boy's mother took him to Peru - and authorities say they are powerless to act",
      "source": "Mail Online",
      "date": "2026-10-01",
      "summary": "A British father says he may never see his six‑year‑old son again after the mother took him to Peru, and officials claim they cannot intervene."
    },
    {
      "id": 520366060,
      "country": "Thailand",
      "country_code": "THA",
      "city": "Bangkok",
      "lat": 13.6485,
      "lng": 100.3881,
      "headline": "Thailand video news | Hail falls in Bangkok as heavy rain hits several areas, Maya bay reopens after two-month conservation closure",
      "source": "Thaiger",
      "date": "2026-10-02",
      "summary": "Hail and heavy rain damaged parts of Bangkok, an electric SUV crashed into a shrine injuring three people, and Maya Bay reopened after a conservation closure."
    },
    {
      "id": 652694662,
      "country": "Thailand",
      "country_code": "THA",
      "city": "Bangkok",
      "lat": 13.7008,
      "lng": 100.3974,
      "headline": "DP World Expands Contract Logistics Network in Thailand with New Bang Na Distribution Centre",
      "source": "The Manila Times",
      "date": "2026-10-02",
      "summary": "DP World opened a new 10,000‑square‑metre distribution centre in Bang Na to expand its contract logistics network."
    },
    {
      "id": 478054930,
      "country": "Thailand",
      "country_code": "THA",
      "city": "Bangkok",
      "lat": 13.7635,
      "lng": 100.3852,
      "headline": "Through the Lens: Thailand floods leave capital in turmoil",
      "source": "Biztoc",
      "date": "2026-10-02",
      "summary": "Torrential rains flooded Bangkok, turning streets into rivers and leaving residents wading through waist‑deep water."
    },
    {
      "id": 753061483,
      "country": "Thailand",
      "country_code": "THA",
      "city": "Bangkok",
      "lat": 13.7171,
      "lng": 100.5441,
      "headline": "Thailand steps up flood response",
      "source": "Sarawak Tribune",
      "date": "2026-10-02",
      "summary": "Thailand is strengthening its flood response, with the Prime Minister directing agencies to coordinate emergency measures for vulnerable groups ahead of forecast heavy rains."
    },
    {
      "id": 266765275,
      "country": "Thailand",
      "country_code": "THA",
      "city": "Bangkok",
      "lat": 13.693,
      "lng": 100.4403,
      "headline": "Protecting Yourself From SMS Scams in Thailand",
      "source": "Ctn News - Chiang Rai Times",
      "date": "2026-10-02",
      "summary": "SMS scams in Thailand target residents and visitors, sending urgent texts claiming delivery delays or bank account risks, urging people to pause before responding."
    },
    {
      "id": 737424589,
      "country": "Albania",
      "country_code": "ALB",
      "city": "Tirana",
      "lat": 41.345,
      "lng": 19.9298,
      "headline": "Ursula von der Leyen: EU accession goal is on the horizon for Albania",
      "source": "European Western Balkans",
      "date": "2026-10-01",
      "summary": "Ursula von der Leyen visited Albania on a Western Balkans tour and discussed Albania's leading position in the EU accession process with Prime Minister Edi Rama."
    },
    {
      "id": 889892680,
      "country": "Albania",
      "country_code": "ALB",
      "city": "Tirana",
      "lat": 41.2518,
      "lng": 19.8706,
      "headline": "Albania PM Defends Trump-Linked Resort As Protesters Fight Luxury Development",
      "source": "Worthy Christian News",
      "date": "2026-09-30",
      "summary": "Albania’s prime minister warned protesters that the outcome of a large tourism project linked to Donald Trump’s family would be decided by an environmental impact assessment instead of public opinion."
    },
    {
      "id": 349035359,
      "country": "Mongolia",
      "country_code": "MNG",
      "city": "Ulaanbaatar",
      "lat": 47.9889,
      "lng": 106.7801,
      "headline": "Mongolia considers COMAC C919 for MIAT fleet renewal",
      "source": "Air Data News",
      "date": "2026-10-01",
      "summary": "The government is assessing the COMAC C919 as a possible option for the national carrier's fleet renewal."
    },
    {
      "id": 83435901,
      "country": "Mongolia",
      "country_code": "MNG",
      "city": "Ulaanbaatar",
      "lat": 47.8812,
      "lng": 106.9711,
      "headline": "Minister of Defense of Mongolia invites Minister of Defense of Japan Shinjiro Koizumi to visit Mongolia",
      "source": "Akipress",
      "date": "2026-10-01",
      "summary": "The Minister of Defense of Mongolia invited the Minister of Defense of Japan to visit Mongolia."
    },
    {
      "id": 668878881,
      "country": "Mongolia",
      "country_code": "MNG",
      "city": "Ulaanbaatar",
      "lat": 47.7531,
      "lng": 106.8723,
      "headline": "Fuel shortage sparks protests in Mongolia",
      "source": "Newsmn",
      "date": "2026-10-01",
      "summary": "Fuel shortages have led some drivers to spend nights sleeping in vehicles or waiting in long queues at filling stations, sparking protests."
    }
  ]
};
